services:
  ai-light-show:
    build: .
    ports:
      - "5500:5500"
    network_mode: host
    volumes:
      - ./songs:/app/static/songs
      - ./fixtures:/app/static/fixtures
    restart: unless-stopped