services:
  light-show:
    build: .
    ports:
      - "5500:5500"
    networks:
      - ailightshow
    depends_on:
      - song-analysis
    volumes:
      - ./songs:/app/static/songs
      - ./fixtures:/app/static/fixtures
      - ./.cache:/root/.cache
    restart: unless-stopped
    environment:
      - SONG_ANALYSIS_SERVICE_URL=http://song-analysis:8001

  song-analysis:
    build:
      context: ./song_analysis
      dockerfile: Dockerfile
    networks:
      - ailightshow
    volumes:
      - ./songs:/app/static/songs
      - ./.cache:/app/cache
    restart: unless-stopped
    ports:
      - "8001:8001" 

  llm-server:
    image: ollama/ollama
    networks:
      - ailightshow
    volumes:
      - ./.ollama_data:/root/.ollama
    restart: unless-stopped
    command: serve
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama:

networks:
  ailightshow:
    driver: bridge