# Docker Compose override for development
# Use this file for development-specific configurations
# 
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  ai-light-show:
    volumes:
      # Mount source code for live reloading
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - DEBUG=true
      - RELOAD=true

  song-analysis:
    volumes:
      # Mount source code for development
      - ./song_analysis:/app
      # Mount songs with write access for development
      - ./songs:/app/songs
    environment:
      - DEBUG=true
      - RELOAD=true
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Development database (if needed)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=ai_light_show
  #     - POSTGRES_USER=dev
  #     - POSTGRES_PASSWORD=dev
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
