version: "3.9"
services:
  ai-light-show:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./songs:/app/static/songs
      - ./fixtures:/app/static/fixtures
    restart: unless-stopped